---
- hosts: "*"
  become: yes
  tasks:
    - name: apt
    apt:
      update_cache: yes
      upgrade: 'yes'
    - name: install core packages
    apt:
      name:
        - ne
        - net-tools
      update_cache: yes