---
- name: Install ne and net-tools
  hosts: "*"
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
     - name: Install ne and net-tools
      apt:
        name:
          - ne
          - net-tools
        state: present