---
- name: Install ne and net-tools
  hosts: "*"
  become: true
  tasks:
    - name: Update apt cache (for Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'
     - name: Install ne and net-tools (for Debian/Ubuntu)
      apt:
        name:
          - ne
          - net-tools
        state: present